### PR TITLE
Bump to xamarin/xamarin-android@2c7d72d2

### PR DESCRIPTION
**Pull request by pjcollins**
Notable documentation related generator changes:

 * xamarin/java.interop@e1ee4b1c: [Java.Interop.Tools.JavaSource] Parse {@param} tags
 * xamarin/java.interop@07c95e96: [Java.Interop.Tools.JavaSource] Parse `<code/>` tags

Changes in xamarin-android and java.interop:

 * https://github.com/xamarin/xamarin-android/compare/ca8f5617cc55cc3510a61433d8d50c6a58ec0ac2...2c7d72d2471d98ca0da910189b8ca849658a8561
 * https://github.com/xamarin/java.interop/compare/a0728ed5b4e2eb91c2c8048b70c221f19c4b6474...e1ee4b1c3731295d80cfa7de418e0edd06ccd98a

### CODE REVIEW

**Review by jonathanpeppers — COMMENTED** [review]
Do we want to address the warnings above? They might actually be typos in the docs that refer to other types?

**Comment by pjcollins** [comment]
> Do we want to address the warnings above? They might actually be typos in the docs that refer to other types?

I've been trying to chip away at these through improvements to java.interop:
```
Total Build Warnings
1114

Total Build Suggestions
891
```
There is a lot to fix though, and the only strict goal I have right now with respect to the docs build report is to ensure that new PRs don't make these numbers worse. The numbers in this report are the same as the [report from the last major PR](https://buildapi.docs.microsoft.com/Output/PullRequest/21733b28-2323-4f2d-1464-e811a8b81c4a/202210031444096124-39/BuildReport?accessString=f20ce94c48ec120fa8b789a2dc77d09d194c7e516ff5b8117c65881b32e2ef70).

**Review by jonathanpeppers — APPROVED** [review]
The main thing I see here is `&lt;code&gt;` changed to `<c>`.

There is anything else that changed in the giant diff? 😄

**Comment by pjcollins** [comment]
There is also a fix for a few dozen cases where duplicate `param`s were defined. Those extra param elements were replaced with a nested `paramref` element instead (https://github.com/xamarin/android-api-docs/pull/41/files#diff-18564fa5cda8d8249b99da1017644a77442722a7c1c3a6e243f3e3254854b146R7120)

**Pull request merged**
