### PR TITLE
Fix code fencing

### PR DESCRIPTION
**Pull request by gewarren**
See https://learn.microsoft.com/en-us/dotnet/api/java.util.stringtokenizer.counttokens?view=xamarin-android-sdk-12#java-util-stringtokenizer-counttokens.

### CODE REVIEW

**Comment by gewarren** [comment]
cc @pjcollins @lobrien

**Comment by pjcollins** [comment]
@gewarren thanks for this update, though I think we have ~7000 instances of this throughout our docs. I recently tried to fix this in our docs generator - https://github.com/xamarin/java.interop/pull/1044. I should have a PR to fix this more broadly shortly, hopefully that one will also cover this case.

**Comment by pjcollins** [comment]
This will be fixed by https://github.com/xamarin/android-api-docs/pull/41/files#diff-c1aa65cc21b687494a906a302af405a8ab9c0c915c37050bb88c114475537db5R214

**Comment by pjcollins** [comment]
Thanks again, closing now that this has been fixed as part of https://github.com/xamarin/android-api-docs/commit/bbc9c91907e57bd8e7f6b85b8292f2b4f09e2438.

**Pull request closed without merging**
