### PR TITLE
Import documentation for API-31

### PR DESCRIPTION
**Pull request by pjcollins**
Replaces: https://github.com/xamarin/android-api-docs/pull/23
Context: https://github.com/xamarin/xamarin-android/pull/5485
Context: https://github.com/xamarin/xamarin-android/commit/a7413a2389886082c3d3422c50a7e6cc84f43d8f

Update the `Mono.Android.dll` documentation, importing the
Google-provided [API-31 Javadoc documentation][0].

At this time, only the following documentation is imported:

  * `<param/>`: The Javadoc `@param` block tag.
  * `<returns/>`: The Javadoc `@returns` block tag.
  * `<summary/>`: First sentence in Javadoc comment.

Additionally, the following information is generated:

  * Documentation Copyright notification
  * HTML Link to the Android documentation for the member.

Note that the link to Android documentation may not work; there are
known issues around the use of generic types. 

The perfect is the enemy of the good (enough)!  It's been 4+ years
since the last documentation import.  Let's get *something* newer.

[0]: http://dl.google.com/android/repository/sources-31_r01.zip

### CODE REVIEW

**Comment by pjcollins** [comment]
@davidbritch @jonpryor unfortunately this initial docs update is going to be mostly un-reviewable, but I think the best course of action is to land this sooner than later. This update will allow us to iterate on smaller fixes that will be more testable and reviewable.

Commit message draft (edited from #23):

```
Context: https://github.com/xamarin/xamarin-android/pull/5485
Context: https://github.com/xamarin/xamarin-android/commit/a7413a2389886082c3d3422c50a7e6cc84f43d8f

Update the `Mono.Android.dll` documentation, importing the
Google-provided [API-31 Javadoc documentation][0].

At this time, only the following documentation is imported:

  * `<param/>`: The Javadoc `@param` block tag.
  * `<returns/>`: The Javadoc `@returns` block tag.
  * `<summary/>`: First sentence in Javadoc comment.

Additionally, the following information is generated:

  * Documentation Copyright notification
  * HTML Link to the Android documentation for the member.

Note that the link to Android documentation may not work; there are
known issues around the use of generic types. 

The perfect is the enemy of the good (enough)!  It's been 4+ years
since the last documentation import.  Let's get *something* newer.

[0]: http://dl.google.com/android/repository/sources-31_r01.zip
```

**Comment by pjcollins** [comment]
Comparing the build results from [master][0] to the [latest build in this PR][1] shows a pretty similar amount of warnings and suggestions given the scope of change, so this should be getting close. The only thing that I am curious about in the PR build summary is the fact that the "Total Files" (92216) value did not match the "Total Published Files" (92215) value. I'm not sure if this is a cause for concern.

After further review of some of the changes introduced with the `mdoc` NuGet package bump, it appears that [F# type syntax is being shown instead of C#][2] which will need to be fixed...

[0]: https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C21733b28-2323-4f2d-1464-e811a8b81c4a%5CPullRequest%5C202111111717164406-27%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T17%3A27%3A10Z&sr=b&sp=r&sig=i%2BdchzpL9dySnwO6fjb1UnTOc54ll%2Bu6J8poNeYD9Ds%3D
[1]: https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C21733b28-2323-4f2d-1464-e811a8b81c4a%5CPullRequest%5C202111121920248621-26%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T19%3A41%3A40Z&sr=b&sp=r&sig=qE9RYp90KMOfdwoeWUyPrDXQgx34kqxHOtK4W%2FOHxE8%3D
[2]: https://review.docs.microsoft.com/en-us/dotnet/api/android.app.activity.actionbar?view=xamarin-android-sdk-12&branch=pr-en-us-26

**Comment by davidbritch** [comment]
I don't think the total published files is a cause for concern. Aside from anything else, the total content files is 92214.

**Comment by pjcollins** [comment]
I think this should be ready for a final (high level) review, I can squash and merge it at some point this week if there is nothing else that looks out of place.

**Comment by davidbritch** [comment]
Looks good to me. I'm asking how we can default the language drop-down to C#, for new users. But that shouldn't block publishing this PR.

Once it's published I'll deprecate the previous monikers.

**Pull request merged**
