### PR TITLE
Moniker update

### PR DESCRIPTION
**Pull request by lobrien**
This is an attempt to fix https://github.com/MicrosoftDocs/feedback/issues/1584#event-2395692733 by simply renaming the frameworksindex file. That might be too simplistic, but I don't know a way to test without being in `live` and asking for a reindex.

### CODE REVIEW

**Comment by lobrien** [comment]
For some reason, this branch didn't seem to incorporate your f78f9129 of 4/11 even though the file deletions show in history.

**Comment by conceptdev** [comment]
Gotcha. Will take a look with fresh eyes in the morning. I agree the approach (renaming the xml) is worth a try!

**Comment by v-alje** [comment]
Docs Build status updates of commit _[88e7149](https://github.com/xamarin/android-api-docs/pull/18/commits/88e7149c2f0aca96b0586ccedfe0b1a5ebc8baeb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[XamarinAndroidAPI/_zip/msdn.4.5.2.zip](https://github.com/xamarin/android-api-docs/blob/moniker_update/XamarinAndroidAPI/_zip/msdn.4.5.2.zip) | :white_check_mark:Succeeded | |
[XamarinAndroidAPI/breadcrumb/toc.yml](https://github.com/xamarin/android-api-docs/blob/moniker_update/XamarinAndroidAPI/breadcrumb/toc.yml) | :white_check_mark:Succeeded | |
[XamarinAndroidAPI/docfx.json](https://github.com/xamarin/android-api-docs/blob/moniker_update/XamarinAndroidAPI/docfx.json) | :white_check_mark:Succeeded | |
[XamarinAndroidAPI/xml/_filter.xml](https://github.com/xamarin/android-api-docs/blob/moniker_update/XamarinAndroidAPI/xml/_filter.xml) | :white_check_mark:Succeeded | |
[docs/Mono.Android/en/FrameworksIndex/xamarin-android-sdk-9.xml](https://github.com/xamarin/android-api-docs/blob/moniker_update/docs/Mono.Android/en/FrameworksIndex/xamarin-android-sdk-9.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C25%5C21733b28-2323-4f2d-1464-e811a8b81c4a%5CPullRequest%5C201906250047472807-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H87R5xMN4xG%2FpLsW1eeY%2B2DBeKbEduvYabvg7DJb1rc%3D&st=2019-06-25T01%3A23%3A11Z&se=2019-07-26T01%3A28%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-alje** [comment]
Docs Build status updates of commit _[ee0949d](https://github.com/xamarin/android-api-docs/pull/18/commits/ee0949d0443562797db7af0436ce0b1ff8cf792d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Mono.Android/en/FrameworksIndex/xamarin-android-sdk-9.xml](https://github.com/xamarin/android-api-docs/blob/moniker_update/docs/Mono.Android/en/FrameworksIndex/xamarin-android-sdk-9.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C25%5C21733b28-2323-4f2d-1464-e811a8b81c4a%5CPullRequest%5C201906250103352479-18%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RL5yTMyCIZ%2FRfX9CsQx7hX%2FSDhrCyzXd9MwoWlzEUbA%3D&st=2019-06-25T02%3A01%3A32Z&se=2019-07-26T02%3A06%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
